# Analysis of Behavioral Data

Analyze the behavioral data and pay attention to whether the subjects show Simon effect and PC effect. 
Perform a three-way ANOVA on the data and view the results.

```{r}
library(tidyverse)
library(broom)
library(flextable)
library(apa)
library(here)
library(ggplot2)
library(rstatix)
library(ggpubr)
library(patchwork)
library(gghalves)
```

## 0. Data reading

```{r}
raw_data <- read_csv(here("data", "input",
                          "all_data_with_RL_BL_estimate_result.csv"))

## Remove RT's outlier and error trials by condition
data_without_error <- filter(raw_data, Type == "hit")
data_without_outlier <- data_without_error %>%
                        group_by(Subject, congruency, prop, condition) %>%
                        filter(abs(RT - mean(RT)) < (sd(RT) * 3))


data_without_outlier %>%
  group_by(prop, condition, congruency) %>%
  summarise(meanRT = mean(RT)) -> to_mean_RT
to_mean_RT %>%
  pivot_wider(names_from = congruency, values_from = meanRT) %>%
  mutate(Simon = inc - con)
```

## 1. Anova

### 1.1 RT

```{r}
library(car)
RA_RT_anova <- data_without_outlier %>%
    group_by(Subject_num, congruency, prop, condition) %>%
    summarise(mean_rt = mean(RT)) %>%
    as_tibble()
RA_RT_anova %>%
  pivot_wider(names_from = c(condition, prop, congruency), values_from = mean_rt) -> foo
mod <- Anova(lm(mean_rt ~ factor(congruency) * factor(prop) * factor(condition), 
                data = RA_RT_anova), type = 3)
mod
RT_anova_table <- RA_RT_anova %>%
    anova_test(dv = mean_rt, wid = Subject_num,
               within = c(congruency, prop, condition)) %>%
    get_anova_table()
RT_anova_table

print("== Describe data ==")

psych::describeBy(RA_RT_anova ~ congruency + prop)
```

Check if the Simon effect can predict the MC/MI condition
```{r}
data_without_outlier %>%
    select(Subject, congruency, RT, prop) %>%
    group_by(Subject, congruency, prop) %>%
    summarise(meanRT = mean(RT)) %>%
    pivot_wider(names_from = congruency, values_from = meanRT) %>%
    mutate(simon_effect = (inc - con)) %>%
    glm(as.factor(prop) ~ simon_effect, data = ., family = "binomial") %>%
    summary()
```

#### Plot

```{r}
RA_RT_anova$prop <- as.factor(RA_RT_anova$prop) %>% 
                      str_replace("20", "MI") %>% 
                      str_replace("80", "MC") %>%
                      fct_relevel("MC", "MI")
RA_RT_anova$condition <- RA_RT_anova$condition %>%
                           str_replace("s", "Stable") %>%
                           str_replace("v", "Volatile")
data_forplot <- unite(RA_RT_anova, col = "factor",
                      prop, congruency, sep = "_", remove = FALSE)
data_forplot$factor <- as.factor(data_forplot$factor)
anova_RT_plot_bar <- ggbarplot(data_forplot,
                               x = "factor", y = "mean_rt",
                               fill = "congruency", color = "congruency",
                               add = "mean_se",
                               facet.by = "condition", xlab = " ",
                               ylab = "RTs (ms)", ylim = c(400, 550),
                               add.params = list(color = "black"),
                               font.label = list(size = 14)) + 
  scale_x_discrete(labels=c('MC', 'MC', 'MI', 'MI')) + 
  scale_fill_discrete(labels = c("Congruent","Incongruent")) +
  scale_color_discrete(labels = c("Congruent","Incongruent")) +
  theme(text = element_text(size = 15), 
        legend.title= element_blank())  
anova_RT_plot_bar 
ggsave(here("data", "output", "plot",
            "anova_RT_plot.png"),
        plot = anova_RT_plot_bar,
        dpi = 300, scale = 2.5, width = 8, height = 4, units = "cm")
```

#### Simple Effect

```{r}
data_without_outlier %>%
    filter(prop == 80) %>%
    group_by(Subject_num, congruency) %>%
    summarise(mean_rt = mean(RT), .groups = "drop") %>%
    pivot_wider(names_from = "congruency",
                values_from = "mean_rt") -> foo1
get_summary_stats(foo1)
t.test(x = foo1$con, y = foo1$inc, alternative = "less", paired = TRUE) %>% t_apa()

data_without_outlier %>%
    filter(prop == 20) %>%
    group_by(Subject_num, congruency) %>%
    summarise(mean_rt = mean(RT), .groups = "drop") %>%
    pivot_wider(names_from = "congruency",
                values_from = "mean_rt") -> foo2
get_summary_stats(foo2)
t.test(x = foo2$con, y = foo2$inc, alternative = "greater", paired = TRUE) %>% t_apa()
```

### Error rate

#### Anova
```{r}
raw_data %>%
    mutate(correct_action = if_else(.data$Type == "hit", 1, 0)) %>%
    group_by(Subject_num, congruency, prop, condition) %>%
    summarise(mean_error_action = (1 - mean(correct_action)) * 100, .groups = "drop") -> error_rate_table

error_rate_table %>%
    anova_test(dv = mean_error_action, wid = Subject_num,
               within = c(congruency, prop, condition)) -> error_rate_anova_table
psych::describe(error_rate_table ~ congruency + prop)
error_rate_anova_table

#output anova result
set_flextable_defaults(digits = 3)
save_as_docx("RT" = flextable(RT_anova_table), 
             "error_rate" = flextable(error_rate_anova_table), 
             path = here("data", "output", "plot", "anova_table.docx"))
```

#### Plot
```{r}
raw_data$prop <- as.factor(raw_data$prop) %>% 
                      str_replace("20", "MI") %>% 
                      str_replace("80", "MC") %>%
                      fct_relevel("MC", "MI")
raw_data$condition <- raw_data$condition %>%
                       str_replace("s", "Stable") %>%
                       str_replace("v", "Volatile")
raw_data  %>%
    mutate(correct_action = if_else(.data$Type == "hit", 1, 0)) %>%
    group_by(Subject_num, congruency, prop, condition) %>%
    summarise(mean_error_action = (1 - mean(correct_action)) * 100, .groups = "drop") %>%
    unite(col = "factor", prop, congruency, sep = "_", remove = FALSE) -> error_rate_forplot
error_rate_plot_bar <- ggbarplot(error_rate_forplot,
                                 x = "factor", y = "mean_error_action",
                                 order = c("MC_con", "MC_inc", "MI_con", "MI_inc"),
                                 fill = "congruency", color = "congruency",
                                 add = "mean_se",
                                 facet.by = "condition",
                                 ylab = "Error rate (%)", xlab = " ",
                                 ylim = c(0.3, 6.5),
                                 add.params = list(color = "black"),
                                 font.label = list(size = 14)) +
  scale_x_discrete(labels=c('MC', 'MC', 'MI', 'MI')) + 
  scale_fill_discrete(labels = c("Congruent","Incongruent")) +
  scale_color_discrete(labels = c("Congruent","Incongruent")) +
  theme(text = element_text(size = 15), legend.title= element_blank())  
error_rate_plot_bar
ggsave(here("data", "output", "plot",
            "anova_error_rate_plot.png"),
            plot = error_rate_plot_bar,
            dpi = 300, scale = 2.5, width = 8, height = 4, units = "cm")
```

## 2. Simon Effect 及其反转

### RT

```{r}
data_add_simon_effect <- data_without_outlier %>%
    group_by(Subject_num, congruency, prop, condition) %>%
    summarise(mean_rt = mean(RT)) %>%
    pivot_wider(names_from = congruency, values_from = mean_rt) %>%
    mutate(simon_effect = inc - con)
data_add_simon_effect$prop <- as.factor(data_add_simon_effect$prop) %>% 
                                str_replace("20", "MI") %>% 
                                str_replace("80", "MC") %>%
                                fct_relevel("MC", "MI")
data_add_simon_effect$condition <- data_add_simon_effect$condition %>%
                                   str_replace("s", "Stable") %>%
                                   str_replace("v", "Volatile")
data_add_simon_effect %>%
    as_data_frame() %>%
    select(-con, -inc) %>%
    ggbarplot(x = "prop", y = "simon_effect", fill = "prop", color = "prop",
              ylab = "Simon effect (ms)", facet.by = "condition", 
              add = "mean_se", add.params = list(color = "black"),
              font.label = list(size = 14),
              palette = "Paired",
              xlab = " ") + 
              geom_hline(yintercept = 0, linetype = 1, size = 0.5)  + 
              rremove("legend") + 
  theme(text = element_text(size = 15))  -> simon_RT_plot
simon_RT_plot
ggsave(here("data", "output", "plot",
            "simon_RT_plot.png"),
            plot = simon_RT_plot,
            dpi = 300, scale = 2.5, width = 8, height = 3, units = "cm")
psych::describeBy(data_add_simon_effect ~ prop)
```

### Error Rate

```{r}
foo <- raw_data
foo$prop <- as.factor(foo$prop) %>% 
                           str_replace("20", "MI") %>% 
                           str_replace("80", "MC") %>%
                           fct_relevel("MC", "MI")
foo$condition <- foo$condition %>%
                 str_replace("s", "Stable") %>%
                 str_replace("v", "Volatile")
foo %>%
    mutate(correct_action = if_else(.data$Type == "hit", 1, 0)) %>%
    group_by(Subject_num, congruency, prop, condition) %>%
    summarise(mean_error_action = (1 - mean(correct_action)) * 100) %>%
    pivot_wider(names_from = congruency, values_from = mean_error_action) %>%
    mutate(simon_effect_error = inc - con) %>%
    select(-con, -inc) %>%
    ggbarplot(x = "prop", y = "simon_effect_error", 
              fill = "prop", color = "prop",
              ylab = "Simon effect (%)", facet.by = "condition", 
              add = "mean_se", add.params = list(color = "black"),
              font.label = list(size = 14),
              palette = "Paired", xlab = " ") + 
              geom_hline(yintercept = 0, linetype = 1, size = 0.5)  + 
              rremove("legend") + 
  theme(text = element_text(size = 15))  -> simon_error_rate_plot
simon_error_rate_plot
```

## 3. Delta plot


```{r}
for_delta_plot <- data_without_outlier
con_data <- filter(for_delta_plot, congruency == "con")
inc_data <- filter(for_delta_plot, congruency == "inc")
result_list <- list()
result_count <- 1

for (sub in unique(for_delta_plot$Subject_num)) {
  for (cond in unique(for_delta_plot$condition)) {
     for (prop_i in unique(for_delta_plot$prop)) {
        sub_con_data <- filter(con_data, Subject_num == sub, 
                               condition == cond, prop == prop_i) %>% 
          arrange(RT)
        sub_inc_data <- filter(inc_data, Subject_num == sub, 
                               condition == cond, prop == prop_i) %>% 
          arrange(RT)
        
        # 三等分变量
        quantile_con <- quantile(sub_con_data$RT, probs = c(1,2,3)/3)
        quantile_inc <- quantile(sub_inc_data$RT, probs = c(1,2,3)/3)
        
        # 分别计算每部份的 Simon 效应
        inc_quant1_idx = sub_inc_data$RT <= quantile_inc[1]
        con_quant1_idx = sub_con_data$RT <= quantile_con[1]
        RT_part_1 <- mean(sub_inc_data$RT[inc_quant1_idx]) - 
                        mean(sub_con_data$RT[con_quant1_idx])
        RT_means_1 <- mean(c(sub_inc_data$RT[inc_quant1_idx],
                             sub_con_data$RT[con_quant1_idx]))
        
        inc_quant2_idx = sub_inc_data$RT <= quantile_inc[2] &
                           sub_inc_data$RT > quantile_inc[1]
        con_quant2_idx = sub_con_data$RT <= quantile_con[2] &
                           sub_con_data$RT > quantile_con[1]
        RT_part_2 <- mean(sub_inc_data$RT[inc_quant2_idx]) - 
                        mean(sub_con_data$RT[con_quant2_idx])
        RT_means_2 <- mean(c(sub_inc_data$RT[inc_quant2_idx], 
                             sub_con_data$RT[con_quant2_idx]))
        
        inc_quant3_idx = sub_inc_data$RT <= quantile_inc[3] &
                           sub_inc_data$RT > quantile_inc[2]
        con_quant3_idx = sub_con_data$RT <= quantile_con[3] &
                           sub_con_data$RT > quantile_con[2]
        RT_part_3 <- mean(sub_inc_data$RT[inc_quant3_idx]) - 
                        mean(sub_con_data$RT[con_quant3_idx])
        RT_means_3 <- mean(c(sub_inc_data$RT[inc_quant3_idx], 
                             sub_con_data$RT[con_quant3_idx]))
        
        result_list[[result_count]] <- cbind(sub, cond, prop_i, 
                                             Simon_Part_1 = RT_part_1, 
                                             Simon_Part_2 = RT_part_2, 
                                             Simon_Part_3 = RT_part_3,
                                             RT_means_1, 
                                             RT_means_2, 
                                             RT_means_3)
        result_count = result_count + 1
     }
  }
}
```

```{r}
# 聚合数据

calc_se_lower <- function(data){
    sd_data <- sd(data)
    se_data <- sd_data / sqrt(length(data))
    return(mean(data) - se_data)
}
calc_se_upper <- function(data){
    sd_data <- sd(data)
    se_data <- sd_data / sqrt(length(data))
    return(mean(data) + se_data)
}

table_delta_plot <- do.call(rbind.data.frame, result_list) 
Simon_part <- select(table_delta_plot, sub, cond, prop_i,
                     starts_with("Simon_")) %>%
              pivot_longer(starts_with("Simon_Part"), 
                           names_to = "part", 
                           values_to = "Simon_effect") 
Simon_part$Simon_effect <- Simon_part$Simon_effect %>% as.numeric()
Simon_part %>%
  group_by(cond, prop_i, part) %>%
  summarise(Simon_effect_n = mean(Simon_effect),
            Lower = calc_se_lower(Simon_effect), 
            Upper = calc_se_upper(Simon_effect)) %>%
  separate(part, into = c("A", "B", "part"), sep = "_") %>%
  select(-A, -B)-> foo

RT_part <- select(table_delta_plot, sub, cond, prop_i,
                     starts_with("RT_")) %>%
            pivot_longer(starts_with("RT_means"), 
                                     names_to = "part", 
                                     values_to = "mean_RT") 
RT_part$mean_RT <- RT_part$mean_RT %>% as.numeric()
RT_part %>%
  group_by(cond, prop_i, part) %>%
  summarise(mean_RT_n = mean(mean_RT)) %>%
  separate(part, into = c("A", "B", "part"), sep = "_") %>%
  select(-A, -B) -> bar
full_join(foo, bar, by = c("cond", "prop_i", "part")) -> delta_plot_table_RT_2


# 统计分析

## ttest
table_delta_plot %>%
    select(sub:Simon_Part_3) %>%
    pivot_longer(starts_with("Simon_Part"), 
                 names_to = "part", 
                 values_to = "Simon_effect") %>%
                 filter(part == "Simon_Part_1") -> delta_for_ttest_table
delta_for_ttest_table$Simon_effect <- as.numeric(delta_for_ttest_table$Simon_effect) 
t.test(Simon_effect ~ prop_i, data = delta_for_ttest_table, paired = T)
lsr::cohensD(Simon_effect ~ prop_i, data = delta_for_ttest_table)

## Describe
table_delta_plot %>%
    select(sub:Simon_Part_3) %>%
    pivot_longer(starts_with("Simon_Part"), 
                 names_to = "part", 
                 values_to = "Simon_effect") -> foo
foo$Simon_effect <- as.numeric(foo$Simon_effect)
options(pillar.sigfig = 7)
foo %>%
    group_by(part, prop_i) %>%
    summarise(mean_simon = mean(Simon_effect)) %>%
    pivot_wider(values_from = mean_simon, names_from = prop_i) %>%
    mutate(diff = `80` - `20`)
```

```{r}

# 绘图
delta_plot_table_RT_2 %>%
  ggplot(aes(x =  mean_RT_n, y = Simon_effect_n)) +
    geom_point(aes(color = prop_i, shape = cond), size = 4.5) +
    geom_line(aes(color = prop_i, linetype = cond), size = 1.2) +
    geom_errorbar(aes(ymin = Lower, ymax = Upper), 
                  width = 4, size = 1, alpha = 0.8) +
    xlab("Mean RT (ms)") + ylab("Simon effect (ms)") + theme_pubr() + 
    theme(text = element_text(size = 15), 
          legend.title= element_blank()) + 
    scale_color_discrete(labels = c("MI","MC")) +
    scale_shape_discrete(labels = c("Stable", "Volatile")) +
    scale_linetype_discrete(element_blank()) -> plot_delta_plot
plot_delta_plot
```

拼图保存
```{r}
library(patchwork)
simon_p1 <- (anova_RT_plot_bar + error_rate_plot_bar) / (simon_RT_plot +  simon_error_rate_plot)
simon_p1[[2]] <- simon_p1[[2]]  + plot_layout(tag_level = 'new')
simon_p1[[3]] <- simon_p1[[3]]  + plot_layout(tag_level = 'new')
simon_p1[[4]] <- simon_p1[[4]]  + plot_layout(tag_level = 'new')
simon_p2 <- simon_p1 | plot_delta_plot +
  plot_annotation(tag_levels = 'A')  -> beh_result_plot
beh_result_plot
ggsave(here("/Users/dddd1007/Library/CloudStorage/Dropbox/工作/博士工作/撰写论文/JoN投稿/图表/行为结果素材/beh_result_plot.png"),
        plot = beh_result_plot, width = 17.6, height = 8.8, unit = "cm",
        dpi = 500, scale = 1.8)
ggsave(here("/Users/dddd1007/Library/CloudStorage/Dropbox/工作/博士工作/撰写论文/JoN投稿/图表/行为结果素材/for_pub/beh_result_plot.tiff"),
        plot = beh_result_plot, width = 17.6, height = 8.8, unit = "cm",
        dpi = 500, scale = 1.8)
```

统计分析
```{r}
delta_plot_table_RT
delta_plot_table_RT %>% 
  filter(RT_size == "RT_part_2", prop_i == 80) -> foo

foo <- filter(foo, Simon_effect < 100)
ggplot(foo, aes(x = Simon_effect, fill = cond)) +
  geom_density()
s_simon <- filter(foo, cond == "s")$Simon_effect
v_simon <- filter(foo, cond == "v")$Simon_effect
t.test(s_simon, v_simon)

library(coin)
oneway_test(Simon_effect ~ factor(cond), data = foo)
#bin2
delta_plot_table_RT %>% 
  filter(RT_size == "RT_part_2", prop_i == 80, cond == "v") -> part2_v
delta_plot_table_RT %>% 
  filter(RT_size == "RT_part_2", prop_i == 80, cond == "s") -> part2_s

t.test(part2_s$Simon_effect, part2_v$Simon_effect, alternative = "greater")

# bin3
delta_plot_table_RT %>% 
  filter(RT_size == "RT_part_3", prop_i == 80, cond == "v") -> part3_v
delta_plot_table_RT %>%
  filter(RT_size == "RT_part_3", prop_i == 80, cond == "s") -> part3_s
t.test(part3_s$Simon_effect, part3_v$Simon_effect, alternative = "greater")

```